name: conformal-inference-git
channels:
  - r_test
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - anyio=3.3.0
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - atk-1.0=2.36.0
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.9.3
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bleach=3.3.1
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.1
  - click-default-group=1.2.2
  - colorama=0.4.4
  - commonmark=0.9.1
  - conda=4.10.1
  - conda-build=3.21.4
  - conda-package-handling=1.7.3
  - coverage=5.5
  - cryptography=3.4.7
  - curl=7.76.1
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=5.0.9
  - defusedxml=0.7.1
  - distlib=0.3.2
  - entrypoints=0.3
  - expat=2.4.1
  - filelock=3.0.12
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - future=0.18.2
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gdk-pixbuf=2.42.6
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - giflib=5.2.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - glob2=0.7
  - graphite2=1.3.13
  - graphviz=2.47.0
  - gsl=2.6
  - gst-plugins-base=1.14.5
  - gstreamer=1.18.4
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.7.2
  - icu=67.1
  - idna=3.1
  - importlib-metadata=4.6.1
  - importlib_metadata=4.6.1
  - iniconfig=1.1.1
  - ipykernel=5.5.5
  - ipython=7.25.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.10.1
  - jupyterlab=3.0.16
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.6.1
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - latex-dependency-scanner=0.0.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - libarchive=3.5.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.76.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=11.1.0
  - libgd=2.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.3
  - libgomp=11.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblief=0.11.5
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=12.3
  - librsvg=2.50.3
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=11.1.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - lightgbm=3.2.1
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - lzo=2.10
  - make=4.3
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - more-itertools=8.8.0
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nbclassic=0.3.1
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.5
  - notebook=6.4.0
  - nspr=4.30
  - nss=3.67
  - numba=0.53.1
  - numpy=1.21.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=21.0
  - pandas=1.2.4
  - pandoc=2.14.1
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.8.2
  - patchelf=0.11
  - patsy=0.5.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.2.1
  - pixman=0.40.0
  - pkginfo=1.7.1
  - plotly=5.1.0
  - pluggy=0.13.1
  - pony=0.7.14
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.19
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.11.5
  - pycosat=0.6.3
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytask=0.0.14
  - pytask-latex=0.0.12
  - pytask-r=0.0.9
  - pytest=6.2.4
  - pytest-cov=2.12.0
  - python=3.9.4
  - python-dateutil=2.8.2
  - python-graphviz=0.16
  - python-libarchive-c=3.1
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.1.0
  - qt=5.12.9
  - r-abind=1.4_5
  - r-aer=1.2_6
  - r-aod=1.3.1
  - r-assertthat=0.2.1
  - r-backports=1.2.1
  - r-base=3.6.3
  - r-base64enc=0.1_3
  - r-bh=1.75.0_0
  - r-boot=1.3_28
  - r-broom=0.5.2
  - r-bslib=0.2.5.1
  - r-cachem=1.0.5
  - r-car=3.0_2
  - r-cardata=3.0_4
  - r-caret=6.0_88
  - r-cellranger=1.1.0
  - r-class=7.3_19
  - r-cli=1.1.0
  - r-clipr=0.7.1
  - r-cluster=2.0.8
  - r-codetools=0.2_18
  - r-colorspace=1.4_1
  - r-commonmark=1.7
  - r-crayon=1.4.1
  - r-curl=3.3
  - r-data.table=1.14.0
  - r-digest=0.6.27
  - r-dplyr=0.8.0.1
  - r-ellipsis=0.3.2
  - r-essentials=1.4
  - r-evaluate=0.14
  - r-fansi=0.4.0
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-forcats=0.5.1
  - r-foreach=1.5.1
  - r-foreign=0.8_71
  - r-formula=1.2_4
  - r-fs=1.5.0
  - r-generics=0.1.0
  - r-ggplot2=3.1.1
  - r-glmnet=2.0_16
  - r-glue=1.4.2
  - r-gower=0.2.2
  - r-gtable=0.3.0
  - r-haven=2.4.1
  - r-hexbin=1.27.2
  - r-highr=0.8
  - r-hms=1.1.0
  - r-htmltools=0.5.1.1
  - r-htmlwidgets=1.5.3
  - r-httpuv=1.6.1
  - r-ipred=0.9_11
  - r-irdisplay=1.0
  - r-irkernel=1.2
  - r-iterators=1.0.13
  - r-jquerylib=0.1.4
  - r-jsonlite=1.7.2
  - r-kernsmooth=2.23_15
  - r-knitr=1.33
  - r-labeling=0.4.2
  - r-later=1.2.0
  - r-lattice=0.20_44
  - r-lava=1.6.9
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.0
  - r-lme4=1.1_21
  - r-lmtest=0.9_36
  - r-lubridate=1.7.10
  - r-magrittr=2.0.1
  - r-maps=3.3.0
  - r-maptools=1.1_1
  - r-markdown=1.1
  - r-mass=7.3_54
  - r-matrix=1.2_17
  - r-matrixmodels=0.5_0
  - r-mgcv=1.8_28
  - r-mime=0.6
  - r-minqa=1.2.4
  - r-modelmetrics=1.2.2.2
  - r-munsell=0.5.0
  - r-nlme=3.1_139
  - r-nloptr=1.2.2.2
  - r-nnet=7.3_16
  - r-numderiv=2016.8_1.1
  - r-openxlsx=4.1.0
  - r-pbdzmq=0.3_5
  - r-pbkrtest=0.5.1
  - r-pillar=1.6.1
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-plyr=1.8.6
  - r-prettyunits=1.1.1
  - r-proc=1.17.0.1
  - r-prodlim=2019.11.13
  - r-progress=1.2.2
  - r-promises=1.2.0.1
  - r-purrr=0.3.4
  - r-quantmod=0.4.18
  - r-quantreg=5.38
  - r-quantregforest=1.3_7
  - r-r6=2.5.0
  - r-randomforest=4.6_14
  - r-rappdirs=0.3.3
  - r-rbokeh=0.6.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.1
  - r-rcppeigen=0.3.3.9.1
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-recipes=0.1.16
  - r-recommended=3.6.0
  - r-rematch=1.0.1
  - r-repr=1.1.3
  - r-reshape2=1.4.4
  - r-rio=0.5.16
  - r-rjson=0.2.20
  - r-rlang=0.4.11
  - r-rmarkdown=1.12
  - r-rpart=4.1_15
  - r-sandwich=2.5_1
  - r-sass=0.4.0
  - r-scales=1.1.1
  - r-shiny=1.6.0
  - r-sourcetools=0.1.7
  - r-sp=1.4_5
  - r-sparsem=1.77
  - r-spatial=7.3_14
  - r-squarem=2021.1
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=3.2_11
  - r-tibble=2.1.1
  - r-tidyr=0.8.3
  - r-tidyselect=1.1.1
  - r-timedate=3043.102
  - r-tinytex=0.12
  - r-ttr=0.24.2
  - r-utf8=1.1.4
  - r-uuid=0.1_4
  - r-vctrs=0.3.8
  - r-viridislite=0.4.0
  - r-withr=2.4.2
  - r-xfun=0.15
  - r-xtable=1.8_4
  - r-xts=0.12.1
  - r-yaml=2.2.1
  - r-zip=2.0.1
  - r-zoo=1.8_9
  - readline=8.1
  - requests=2.26.0
  - requests-unixsocket=0.2.0
  - rich=10.6.0
  - ripgrep=13.0.0
  - rpy2=3.4.5
  - ruamel_yaml=0.15.80
  - scikit-learn=0.24.2
  - scipy=1.5.3
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - sed=4.8
  - send2trash=1.7.1
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.0.1
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - sysroot_linux-64=2.12
  - tenacity=8.0.1
  - terminado=0.10.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tikzplotlib=0.9.9
  - tk=8.6.10
  - tktable=2.10
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.61.2
  - traitlets=5.0.5
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - tzlocal=2.1
  - urllib3=1.26.6
  - virtualenv=20.0.33
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - alabaster==0.7.12
    - cfgv==3.3.0
    - docutils==0.16
    - identify==2.2.6
    - imagesize==1.2.0
    - latexcodec==2.0.1
    - livereload==2.6.3
    - nodeenv==1.6.0
    - pre-commit==2.13.0
    - pybtex==0.24.0
    - pybtex-docutils==1.0.0
    - snowballstemmer==2.1.0
    - sphinx==4.0.2
    - sphinx-autobuild==2021.3.14
    - sphinx-rtd-theme==0.5.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-bibtex==2.2.1
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5

